#! /bin/sh
set -e

if [ "$1" = remove ]; then
    # Native multiarch packages declare a Replaces: on the corresponding
    # biarch package. Therefore if both a biarch package and the corresponding
    # multiarch package are installed, then the multiarch package is removed,
    # and then the biarch package is removed, the dynamic linker symlink
    # becomes a dangling symlink. Remove it in that case.
    if [ -h /lib/ld-linux.so.2 ] && [ ! -f /lib/ld-linux.so.2 ]; then
        rm /lib/ld-linux.so.2
    fi
fi

if [ "$1" = deconfigure ]; then
    :; # blah, do something useful with ldso
fi

#!/bin/sh
# ESP Package Manager v4.1
rm -rf /opt/brother/PTouch/pj722/cupswrapper
/etc/init.d/cups restart
rm -f /tmp/pj722_latest_print_info


#rmdir --ignore-fail-on-non-empty /opt/brother/PTouch/pj722/lpd
#rmdir --ignore-fail-on-non-empty /opt/brother/PTouch/pj722/inf
#rmdir --ignore-fail-on-non-empty /opt/brother/PTouch/pj722

exit 0
